### ISSUE TITLE
replace SEGVs with routability mode and unidirectional routing

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenROAD#553]
This testcase [replace-segv.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/5756188/replace-segv.tar.gz) SEGVs in replace. It looks to be related to `grt::set_unidirectional_routing 1`. There are a coupe of heap underflow warnings before the SEGV:

```

[INFO] Processing 113086 obstacles on layer 2
[INFO] Processing 32 obstacles on layer 5
Error: heap underflow
Error: heap underflow
...

0x0000000000c62c41 in grt::mazeRouteMSMDOrder3D(int, int, int) ()
(gdb) backtrace 
#0  0x0000000000c62c41 in grt::mazeRouteMSMDOrder3D(int, int, int) ()
#1  0x0000000000c51ba2 in grt::FastRouteCore::run() ()
#2  0x00000000009ccc2c in grt::GlobalRouter::findRouting(std::vector<grt::Net*, std::allocator<grt::Net*> >&) ()
#3  0x00000000009ccd06 in grt::GlobalRouter::runFastRoute(bool) ()
#4  0x000000000049c994 in replace::RouteBase::getGlobalRouterResult() ()
#5  0x000000000049dda0 in replace::RouteBase::routability() ()
#6  0x0000000000481859 in replace::NesterovPlace::doNesterovPlace() ()
#7  0x000000000047674f in replace::Replace::doNesterovPlace() ()
#8  0x000000000047354a in _wrap_replace_nesterov_place_cmd ()
#9  0x00007ffff7e34042 in TclNRRunCallbacks () from /lib64/libtcl8.6.so
#10 0x00007ffff7e39da7 in ?? () from /lib64/libtcl8.6.so
#11 0x00007ffff7e3a5d7 in Tcl_EvalEx () from /lib64/libtcl8.6.so
#12 0x00007ffff7e3a5fa in Tcl_Eval () from /lib64/libtcl8.6.so
```

**Comment by eder-matheus** [comment]
@antonblanchard Fix for the issue will be available in the next update of the public repo.
